# Generated by Django 5.2.7 on 2025-10-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vehicle",
        ),
    ]
