# Generated by Django 5.2.3 on 2025-06-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
