# Generated by Django 5.2.5 on 2025-08-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('brake_service', 'Brake Service'), ('transmission_service', 'Transmission Service'), ('air_filter', 'Air Filter Replacement'), ('cabin_filter', 'Cabin Filter Replacement'), ('tune_up', 'Tune Up'), ('inspection', 'Inspection'), ('repair', 'Repair'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('mileage', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', '-mileage'],
            },
        ),
    ]
