# Generated by Django 5.2.7 on 2025-10-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_servicerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
